import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/Footer";
import OurPartners from "./components/LandingPage/OurGovPartners";

export const metadata = {
  title: "Eupraxis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="min-h-[300px]">
        {children}
        </div>

        <div id="partners" className="text-center py-3 bg-gray-100">
          <OurPartners />
        </div>
        <Footer />
      </body>
    </html>
  );
}
