import LayoutWrapper from "./components/appLayout/LayoutWrapper";
import "./globals.css";

export const metadata = {
  title: "Eupraxis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper children={children} />
      </body>
    </html>
  );
}
